// Pure helpers shared by the service worker, popup, and options page.
// Everything here is side-effect free and unit-tested; the chrome.* calls
// live in background.js so this file stays testable under plain Node.

// Netscape cookie-file field order:
//   domain \t includeSubdomains \t path \t secure \t expiry \t name \t value
// Column 4 is SECURE. TubeArchivist's extension writes httpOnly there; peeq's
// parser reads that column into Cookie.Secure, so copying them would store a
// lie. httpOnly is instead marked by the #HttpOnly_ domain prefix, which
// backend/internal/cookie/netscape.go strips before its comment check.
export function cookieLine(cookie) {
  const domain = cookie.httpOnly ? `#HttpOnly_${cookie.domain}` : cookie.domain;
  const includeSubdomains = cookie.domain.startsWith(".") ? "TRUE" : "FALSE";
  const secure = cookie.secure ? "TRUE" : "FALSE";
  // Chrome reports expirationDate as a float and omits it for session
  // cookies; the file format wants an integer, and 0 means "session".
  const expiry = Number.isFinite(cookie.expirationDate)
    ? Math.trunc(cookie.expirationDate)
    : 0;
  return [domain, includeSubdomains, cookie.path, secure, expiry, cookie.name, cookie.value].join("\t");
}

export function toNetscape(cookies) {
  const lines = [
    "# Netscape HTTP Cookie File",
    "# Generated by peeq Companion. Do not edit.",
    "",
  ];
  for (const cookie of cookies) {
    lines.push(cookieLine(cookie));
  }
  return lines.join("\n") + "\n";
}

// Mirrors backend/internal/cookie/netscape.go Validate: a domain counts as
// YouTube when, with any leading dot removed, it is youtube.com or a
// subdomain of it. Suffix matching alone would accept youtube.com.evil.test.
export function isYouTubeDomain(domain) {
  const bare = domain.startsWith(".") ? domain.slice(1) : domain;
  return bare === "youtube.com" || bare.endsWith(".youtube.com");
}
