// Pure helpers shared by the service worker, popup, and options page.
// Everything here is side-effect free and unit-tested; the chrome.* calls
// live in background.js so this file stays testable under plain Node.

// Netscape cookie-file field order:
//   domain \t includeSubdomains \t path \t secure \t expiry \t name \t value
// Column 4 is SECURE. TubeArchivist's extension writes httpOnly there; peeq's
// parser reads that column into Cookie.Secure, so copying them would store a
// lie. httpOnly is instead marked by the #HttpOnly_ domain prefix, which
// backend/internal/cookie/netscape.go strips before its comment check.
export function cookieLine(cookie) {
  const domain = cookie.httpOnly ? `#HttpOnly_${cookie.domain}` : cookie.domain;
  const includeSubdomains = cookie.domain.startsWith(".") ? "TRUE" : "FALSE";
  const secure = cookie.secure ? "TRUE" : "FALSE";
  // Chrome reports expirationDate as a float and omits it for session
  // cookies; the file format wants an integer, and 0 means "session".
  const expiry = Number.isFinite(cookie.expirationDate)
    ? Math.trunc(cookie.expirationDate)
    : 0;
  return [domain, includeSubdomains, cookie.path, secure, expiry, cookie.name, cookie.value].join("\t");
}

export function toNetscape(cookies) {
  const lines = [
    "# Netscape HTTP Cookie File",
    "# Generated by peeq Companion. Do not edit.",
    "",
  ];
  for (const cookie of cookies) {
    lines.push(cookieLine(cookie));
  }
  return lines.join("\n") + "\n";
}

// Mirrors backend/internal/cookie/netscape.go Validate: a domain counts as
// YouTube when, with any leading dot removed, it is youtube.com or a
// subdomain of it. Suffix matching alone would accept youtube.com.evil.test.
export function isYouTubeDomain(domain) {
  const bare = domain.startsWith(".") ? domain.slice(1) : domain;
  return bare === "youtube.com" || bare.endsWith(".youtube.com");
}

// The gate: backend/internal/cookie/netscape.go Validate accepts a jar when
// at least ONE of these is present on a YouTube domain. This and only this
// decides whether the send button is enabled.
export const GATE_COOKIE_NAMES = ["SID", "__Secure-1PSID", "__Secure-3PSID"];

// The display set is INFORMATIONAL ONLY — the "N of 5" readout. It is a
// superset of the gate. A 3-of-5 jar is valid and must never be blocked.
export const DISPLAY_COOKIE_NAMES = [
  "SID", "__Secure-1PSID", "__Secure-3PSID", "SAPISID", "LOGIN_INFO",
];

export function selectYouTubeCookies(cookies) {
  return cookies.filter((c) => isYouTubeDomain(c.domain));
}

export function hasSessionCookie(cookies) {
  return selectYouTubeCookies(cookies).some((c) => GATE_COOKIE_NAMES.includes(c.name));
}

export function countDisplayCookies(cookies) {
  const present = new Set(
    selectYouTubeCookies(cookies)
      .map((c) => c.name)
      .filter((name) => DISPLAY_COOKIE_NAMES.includes(name)),
  );
  return present.size;
}
