-- category_manual: marks a category the human picked on the Player, so a
-- future bulk reclassification can leave it alone. Everything else on
-- videos.category is classifier output and is safe to recompute.
--
-- The reset below is the whole point of this migration, not an oversight. The
-- category enum grew by eight entries (sports, food, travel, automotive, home,
-- arts, music, politics), and the classify prompt forces a choice — so every
-- existing row was classified against a list that could not express half of
-- them, and a cycling video is sitting in 'entertainment' because nothing
-- better was on offer. Clearing the column IS the backfill: the summarize
-- worker's idle sweep re-classifies whatever is 'uncategorized'.
--
-- The WHERE clause is load-bearing and must keep matching
-- videos.Store.NextUnclassified, which is what the sweep selects on. Only rows
-- that sweep can actually reach may be cleared. A tombstoned video keeps its
-- summary but not its 'downloaded' status, and a no-transcript video has no
-- summary at all; neither is ever offered to the classifier again, so clearing
-- them would not reclassify them, it would erase them into 'uncategorized'
-- permanently. That is especially true of a no-transcript video, where a hand
-- pick on the Player is the ONLY way the category could have been set.
--
-- Within the cleared set, hand picks made before this migration go too. That
-- is accepted, deliberately, and cannot be avoided: those rows carry no flag
-- and are indistinguishable from classifier output. The flag protects picks
-- made from here on.
--
-- Expect the Library to read Uncategorized until the sweep drains: it is one
-- LLM call per video, and it only runs when the summary job queue is empty.
ALTER TABLE videos ADD COLUMN category_manual INTEGER NOT NULL DEFAULT 0;
UPDATE videos SET category = 'uncategorized'
 WHERE status = 'downloaded' AND summary <> '';
