-- Read the inbox that already existed when summaries shipped.
--
-- 0020 added the caption fetcher and, in the same breath, retired every ledger
-- row that existed at the time:
--
--     UPDATE channel_videos SET caption_attempts = 99;
--
-- That was deliberate and it was right. Deploying the feature should not have
-- handed the fetcher a long-neglected inbox all at once — hundreds of yt-dlp
-- calls and hundreds of summaries, unasked for, on videos the user had already
-- scrolled past. "Videos discovered from now on" was the safe default for a
-- feature nobody had seen working yet.
--
-- Now it has been seen working, and the inbox that predates it is exactly the
-- inbox that is hardest to triage: it is full of videos left undecided because
-- a poster and a title were never enough to decide on. So: one pass over it.
--
-- This is the whole backfill. There is no worker to add and nothing to remove
-- afterwards, which is the difference between this and 0018's re-embed
-- backfill (#241, removed in #247 once drained). That one needed a loop written
-- for it. This one does not: captionfetch.Worker already runs on every boot and
-- already does precisely this work — the sentinel above is the only thing that
-- was keeping it away from these rows. A migration runs once per database and
-- never again, so it IS the one-shot mechanism.
--
-- What the fetcher does with these rows is unchanged and needs no special
-- casing here:
--
--   * Only 'pending' rows are ever claimed, so an ignored or already-queued
--     video is not revisited. Hence the first half of the WHERE clause —
--     without it this would also un-retire rows for videos the user has
--     already decided about, and the fetcher would ignore them anyway, but the
--     row would carry a misleading counter forever.
--   * A channel with auto_summary = 0 is skipped, so an opt-out made before
--     this deploy is honoured rather than overridden.
--   * Work is claimed oldest-first at one video per minute, sharing the yt-dlp
--     pacer with scans. A deep inbox drains over hours, not in a burst: 60
--     videos an hour, and a scan is never crowded out.
--   * Old videos are the good case for captions. The retry ladder exists
--     because YouTube's ASR lags publication by minutes to hours; every video
--     here is days or weeks old, so its captions either exist now or never
--     will, and most will settle on the first attempt.
--
-- The NOT EXISTS is the half that is easy to leave out and expensive to leave
-- out, because 99 means two different things.
--
-- 0020 stamps it on rows it retires, and MarkCaptionSettled stamps the same
-- value on every row the fetcher has finished with — including one that tried
-- all five rungs and found no captions. The counter alone cannot tell those
-- apart, so a blanket reset would send the fetcher back to every video it has
-- already established has nothing to read, at five yt-dlp calls each, and end
-- up settling them exactly as before.
--
-- The videos row is what separates them. captionfetch creates it BEFORE its
-- first fetch (so a video whose captions never arrive still has somewhere to
-- record no_transcript), which makes "has no videos row" precisely "peeq has
-- never looked at this video". That is the set this migration is for.
--
-- It also, for free, spares a row that is part-way through its ladder right
-- now: it has a videos row, so it keeps its count and its schedule instead of
-- being handed four extra attempts.
--
-- Setting 0 rather than also clearing next_caption_attempt_at: that column is
-- already NULL for every row this matches — 0020 never wrote it, and a row that
-- has never been claimed has never had an attempt recorded — and NULL already
-- means "due immediately".
UPDATE channel_videos
   SET caption_attempts = 0
 WHERE state = 'pending'
   AND NOT EXISTS (
         SELECT 1 FROM videos v WHERE v.id = channel_videos.video_id
       );
